baseURL = 'https://md-imtiaj.github.io/freeware/'
languageCode = 'en-us'
title = 'Freeware Files'


theme = 'lightbi-hugo'


googleAnalytics = "XXX"
enableRobotsTXT = true
enableGitInfo = false
Paginate = 6

[permalinks]
  posts = '/:slug/'
  tags = '/:slug/'
  
[minify]
  minifyOutput = false
  
[params]
    showRelatedPosts = true #for lightbi related posts
    description = "Free Software Downloads and reviews."
    author = "Md Imtiaj"
    selfHosted = true
	mainSections = ["post","posts"]
	#dateFormat = "2 January 2023"
	comments = false
	readingTime = true
	wordCount = true
	useHLJS = false
	socialShare = true
	delayDisqus = true
	summaryLength  = "9"
	gcse = false
	Lastmod = true
	rss = true 
	pagination = "10"
	hideAuthor = true
	darkMode = false

  [params.mytags]
	go = 'Go is developed by google.'
	php = 'PHP is the most populer language for web developemnt.'



#nav main menu

[[menu.main]]
    name = "HOW-TO's"
    url = "/howto/"
    weight = 1	

[[menu.main]]
    name = "Games"
    url = "/Free-Games/"
    weight = 2

[[menu.main]]
    name = "Essential"
    url = "/Essential-Free-Software/"
    weight = 3


[[menu.main]]
    name = "Top 5"
    url = "/Top-5-Software/"
    weight = 4

	
[[menu.main]]
    name = "Top 100"
    url = "/Top-100-Free-Downloads/"
    weight = 5







#menu for footer

[[menu.footer]]
    name = "Antivirus"
    url = "/Antivirus/"
    weight = 1

[[menu.footer]]
    name = "Audio Video"
    url = "/Audio-Video/"
    weight = 2
	
[[menu.footer]]
    name = "Business Organize"
    url = "/Business-Organize/"
    weight = 3

[[menu.footer]]
    name = "Desktop Enhancements"
    url = "/Desktop-Enhancements-Utilities/"
    weight = 4

[[menu.footer]]
    name = "Developer Tools"
    url = "/Developer-Tools/"
    weight = 5
	
[[menu.footer]]
    name = "Drivers"
    url = "/Drivers/"
    weight = 6	

[[menu.footer]]
    name = "Essential Sofwares"
    url = "/Essential-Free-Software/"
    weight = 7

[[menu.footer]]
    name = "Games"
    url = "/Free-Games/"
    weight = 8
	
[[menu.footer]]
    name = "Graphics Design"
    url = "/Graphics/"
    weight = 9

[[menu.footer]]
    name = "Home Education"
    url = "/Home-Education/"
    weight = 10


[[menu.footer]]
    name = "Internet"
    url = "/Internet/"
    weight = 11
	
[[menu.footer]]
    name = "Mobile Smartphone Tools"
    url = "/Mobile-Smartphone-Tools/"
    weight = 12
	
[[menu.footer]]
    name = "Network"
    url = "/Network-Tools/"
    weight = 13
	
[[menu.footer]]
    name = "Network"
    url = "/Network-Tools/"
    weight = 14
	
[[menu.footer]]
    name = "Programming"
    url = "/Programming/"
    weight = 15
	
[[menu.footer]]
    name = "Screensavers"
    url = "/Screensavers/"
    weight = 16
	
[[menu.footer]]
    name = "Security Privacy"
    url = "/Security-Privacy/"
    weight = 17
	
[[menu.footer]]
    name = "Utilities"
    url = "/Utilities/"
    weight = 18